### ISSUE TITLE
ngx-quill  (Angular 6/7) Support

### ISSUE THREAD

**Issue by hemangsk** [dragonwong/quill-plugin-image-upload#1]
Hi, 

Thanks a ton for this awesome package. I just wanted to ask if the plugin supports ngx-quill https://www.npmjs.com/package/ngx-quill. We have an Angular 6 project where we need the image upload functionality and this plugin will be really helpful therein. Thanks!

**Comment by dragonwong** [comment]
@hemangsk sorry I am not familiar with angular, but I think you can still use this plugin because it was written by pure javascript, no matter what framework you use, angular, react, vue and etc.
